name: Deploy to Deta
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
      env:
        DETA_KEY: ${{ secrets.DETA_PROJECT_TOKEN }}
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: 'Helpboard-V3-API' #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: 'Helpboard' #Optional: Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone